const images = {
    image: require('./image.png'),
    tagPeople: require('./tag-people.png'),
    feeling: require('./feeling.png'),
    checkIn: require('./check-in.png'),
    gif: require('./gif.png'),
    more: require('./three-dots-icon.jpg'),
    onlyMe: require('./only-me.png'),
    happy: require('./tNYZpPkEnbp.png'),
    blessed: require('./C4yAC7LRNGf.png'),
    loved: require('./qcBQ5HblkNF.png'),
    sad: require('./vAd0CBmjF8Y.png'),
    celebrating: require('./1eo2SUFgxCj.png'),
    watching: require('./Qu7tUcfMLQQ.png'),
    eating: require('./BvSNyY4eWn_.png'),
    drinking: require('./Nf-5mtmcdkl.png'),
    friendship: require('./5ooeZJWLOSl.png'),
    aBirthday: require('./Q5DAVMG-eCj.png'),
    yourSpecialDay: require('./Lt9KbIk9NFp.png'),
    birthdays: require('./Q5DAVMG-eCj.png'),
    liveVideo: require('./v1iF2605Cb5.png'),
    lifeEvent: require('./CenxFlWjtJO.png'),
    lock: require('./JgqJqE4kFfK.png'),
    public: require('./KV7QFf-Yspp.png'),
    backgroundLifeEvent: require('./st43MlfQdGP.png'),
    work: require('./tv-E-vHm5BI.png'),
    closeBorder: require('./A_NcMeki4UO.png'),
};

export default images;
