module.exports = {
    ADD_STORY: 'ADD_STORY',
    BIRTHDAY: 'BIRTHDAY',
    POST_TWEET: 'POST_TWEET',
    LIKE_TWEET: 'LIKE_TWEET',
    POST_COMMENT: 'POST_COMMENT',
    LIKE_COMMENT: 'LIKE_COMMENT',
};
